# Generated by Django 4.0.5 on 2023-01-21 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category')),
                ('createddate', models.DateField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['-createddate'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('preview_desc', models.CharField(max_length=255, verbose_name='Sort decription')),
                ('description', models.TextField(max_length=1000, verbose_name='Decription')),
                ('images', models.ImageField(upload_to='products')),
                ('price', models.FloatField()),
                ('old_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('is_stock', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='store.category')),
            ],
            options={
                'ordering': ['-createdate'],
            },
        ),
        migrations.CreateModel(
            name='VariationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.CharField(choices=[('size', 'size'), ('color', 'color')], max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('createdate', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_gellary')),
                ('createdate', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='OurProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='Company Name')),
                ('company_address', models.CharField(max_length=250, verbose_name='Company address')),
                ('about_company', models.CharField(max_length=250, verbose_name='About Company')),
                ('email_adddress', models.CharField(max_length=50, verbose_name='Email adddress')),
                ('contract_number', models.CharField(max_length=15, verbose_name='Contract Number')),
                ('facebook', models.CharField(max_length=250, verbose_name='Facebook')),
                ('twitter', models.CharField(max_length=250, verbose_name='Twitter')),
                ('youtube', models.CharField(max_length=250, verbose_name='Youtube')),
                ('linkedin', models.CharField(max_length=250, verbose_name='Linkedin')),
                ('company_logo', models.ImageField(upload_to='logo')),
                ('fabi_icon', models.ImageField(upload_to='fabi_icon')),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baner_long_image', models.ImageField(upload_to='banner_long')),
                ('baner_short_image', models.ImageField(upload_to='banner_short')),
                ('baner_title', models.CharField(max_length=100, verbose_name='Banner Title')),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='store.product')),
            ],
        ),
    ]
