# Generated by Django 4.0.5 on 2023-01-11 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_variationvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baner_long_image', models.ImageField(upload_to='banner_long')),
                ('baner_short_image', models.ImageField(upload_to='banner_short')),
                ('baner_title', models.CharField(max_length=100, verbose_name='Banner Title')),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='store.product')),
            ],
        ),
    ]
